# Generated by Django 3.0.11 on 2021-12-30 09:41

import codershq.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Event title')),
                ('image', models.ImageField(upload_to=codershq.events.models.event_image_path, verbose_name='Event image')),
                ('date_time', models.DateTimeField(verbose_name='Event date and time')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Event duration (hrs)')),
                ('description', models.TextField(verbose_name='Event description')),
                ('event_link', models.URLField(blank=True, null=True, verbose_name='Event zoom link (only if online)')),
                ('event_location', models.CharField(blank=True, max_length=150, null=True, verbose_name="Event location (use 'Online' if its online)")),
                ('seats', models.IntegerField(blank=True, null=True, verbose_name='Number of seats available (if not online')),
            ],
        ),
    ]
