# Generated by Django 3.2.11 on 2022-01-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220119_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(default=None, max_length=500, verbose_name='Short event description'),
        ),
    ]
