# Generated by Django 3.2.11 on 2022-02-14 13:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requirements',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Event requirements (like PCR, Vaccine, etc)'),
        ),
    ]
