# Generated by Django 3.2.11 on 2022-03-13 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20220313_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_time',
            new_name='start',
        ),
    ]
