# Generated by Django 3.2.11 on 2022-03-13 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_date_time_event_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event end date time'),
            preserve_default=False,
        ),
    ]
