# Generated by Django 3.2.11 on 2022-03-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='short_description',
            new_name='summary',
        ),
    ]
