# Generated by Django 3.2.11 on 2022-03-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_short_description_event_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='seats',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_link',
        ),
    ]
