# Generated by Django 3.2.11 on 2022-03-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20220313_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='listed',
            field=models.BooleanField(default=True, verbose_name='Show event in event list?'),
        ),
        migrations.AddField(
            model_name='event',
            name='online_event',
            field=models.BooleanField(default=False, verbose_name='Is the event online?'),
        ),
        migrations.AddField(
            model_name='event',
            name='show_remaining',
            field=models.BooleanField(default=False, verbose_name='Show the total number of remaining event tickets'),
        ),
    ]
