# Generated by Django 3.2.11 on 2022-03-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20220313_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventbrite_id',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='eventbrite id'),
        ),
    ]
