# Generated by Django 3.2.11 on 2022-09-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220627_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pluralSightEmail',
            field=models.CharField(blank=True, max_length=255, verbose_name='PluralSight Email'),
        ),
    ]
