# Generated by Django 3.0.11 on 2021-02-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210209_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
