# Generated by Django 3.0.11 on 2021-02-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_qualification',
            field=models.CharField(blank=True, max_length=30, verbose_name="User's highest qualification"),
        ),
        migrations.AddField(
            model_name='user',
            name='academic_qualification_file',
            field=models.FileField(blank=True, null=True, upload_to='academic'),
        ),
        migrations.AddField(
            model_name='user',
            name='back_end_score',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv', verbose_name="User's CV"),
        ),
        migrations.AddField(
            model_name='user',
            name='database_score',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='devops_score',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='front_end_score',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='github_profile',
            field=models.CharField(blank=True, max_length=255, verbose_name="User's GitHub profile"),
        ),
        migrations.AddField(
            model_name='user',
            name='github_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_score',
            field=models.IntegerField(default=20),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
