# Generated by Django 3.0.11 on 2021-08-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210805_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cv',
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Enter your name'),
        ),
    ]
