# Generated by Django 3.0.11 on 2021-08-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210805_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_to_create_company',
            field=models.BooleanField(default=True),
        ),
    ]
