# Generated by Django 3.0.11 on 2021-08-20 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210805_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leader_of_teams',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_leader', to='users.Team'),
        ),
    ]
