# Generated by Django 3.0.11 on 2021-02-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210215_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fav_language',
            field=models.CharField(blank=True, max_length=150, verbose_name='Favourite programming language based on GitHub'),
        ),
    ]
