# Generated by Django 3.0.11 on 2021-08-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_leader_of_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='leader_of_teams',
        ),
        migrations.AddField(
            model_name='user',
            name='team_leader',
            field=models.BooleanField(default=False),
        ),
    ]
