# Generated by Django 3.0.11 on 2021-02-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_fav_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_hackathons',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of hackathons completed'),
        ),
    ]
