# Generated by Django 3.0.11 on 2021-08-02 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Challenge')),
                ('description', models.TextField(help_text='Describe the Challenge', max_length=5000, verbose_name='Challenge description')),
                ('logo', models.ImageField(upload_to='challenges/logo/', verbose_name='Challenge Logo')),
                ('github_link', models.TextField(default=None, verbose_name='Challenge github link')),
                ('website', models.TextField(max_length=100, verbose_name='Website link')),
                ('slack_group', models.TextField(default=None, max_length=100, verbose_name='Slack group')),
                ('cloud_provider', models.TextField(default=None, max_length=100, verbose_name='Cloud Provider')),
                ('cloud_provider_url', models.URLField(default=None, verbose_name='Cloud Provider URL')),
                ('cloud_provider_toke', models.TextField(default=None, max_length=500, verbose_name='Cloud Provider token')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100, verbose_name='Category of challenge scoring')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Sprint start date')),
                ('end_date', models.DateField(verbose_name='Sprint end date')),
                ('title', models.TextField(max_length=100, verbose_name='Sprint title')),
                ('description', models.TextField(max_length=5000, verbose_name='Sprint Description')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Sprint score')),
                ('challenge_score_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='challenge.ScoreCategory')),
                ('sprints', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='challenge.Sprint')),
            ],
        ),
    ]
