# Generated by Django 3.0.11 on 2021-08-02 15:04

import autoslug.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title of Challenge')),
                ('subtitle', models.CharField(max_length=150, verbose_name='Little info to explain the Challenge.')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('challenge_type', models.CharField(choices=[('VI', 'Virtual'), ('PH', 'Physical'), ('HY', 'Hybrid')], default=('HY', 'Hybrid'), max_length=2, verbose_name='Challenge Type')),
                ('description', models.TextField(help_text='Describe the Challenge', max_length=5000, verbose_name='Challenge description')),
                ('evaluation', models.TextField(help_text='Describe how will the challenge be evaluated', max_length=5000, verbose_name='Challenge evaluation')),
                ('timeline', models.TextField(help_text="Describe the Challenge's timeline", max_length=5000, verbose_name='Challenge timeline')),
                ('rules', models.TextField(help_text='Describe rules for the challenge', max_length=5000, verbose_name='Challenge rules')),
                ('prizes', models.TextField(help_text='Describe how the prize money will be distributed', max_length=5000, verbose_name='Challenge prize distrebution')),
                ('prize_money', models.PositiveIntegerField(default=0, verbose_name='Total prize money')),
                ('join_date', models.DateField(help_text='When the competitors can start joining', verbose_name='Challenge join date')),
                ('date_start', models.DateField(verbose_name='Challenge start date')),
                ('date_end', models.DateField(help_text='Challenge end date, no competitor can join after this date', verbose_name='Challenge end date')),
                ('last_join_date', models.DateField(help_text='Last date competitors can join', verbose_name='Last join date')),
                ('competitors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
