# Generated by Django 3.2.11 on 2022-02-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='host_name',
            field=models.CharField(default='Majid Al Futtaim', max_length=100, verbose_name='Challenge host name'),
            preserve_default=False,
        ),
    ]
