# Generated by Django 3.2.11 on 2022-01-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20220119_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='logo',
        ),
        migrations.AddField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='challenges/image/', verbose_name='Challenge Image'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='github_link',
            field=models.TextField(blank=True, default=None, verbose_name='Challenge github link'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='website',
            field=models.TextField(blank=True, default=None, max_length=100, verbose_name='Website link'),
        ),
    ]
