# Generated by Django 3.0.11 on 2021-08-20 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0003_challenge_prticipants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='prticipants',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
