# Generated by Django 3.2.11 on 2022-02-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_challenge_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='host_logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Your logo'),
        ),
    ]
