# Generated by Django 3.2.11 on 2022-01-26 17:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20220126_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='cloud_provider',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='cloud_provider_token',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='cloud_provider_url',
        ),
        migrations.AddField(
            model_name='challenge',
            name='short_description',
            field=models.TextField(default='Test data', help_text='Short description of the challenge', max_length=20, verbose_name='Short challenge description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='test_data',
            field=models.URLField(blank=True, help_text='Link to test data set', null=True, verbose_name='Test data link'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='train_data',
            field=models.URLField(blank=True, help_text='Link to train data set', null=True, verbose_name='Train data link'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='github_link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Challenge github link'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, default=None, null=None, upload_to='challenges/image/', verbose_name='Challenge Image'),
        ),
    ]
