# Generated by Django 3.0.11 on 2021-08-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_auto_20210820_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='prticipants',
        ),
    ]
