# Generated by Django 3.2.11 on 2022-01-28 13:36

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0006_auto_20220126_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='user',
        ),
        migrations.AddField(
            model_name='challenge',
            name='evaluation',
            field=ckeditor.fields.RichTextField(default='ee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='short_description',
            field=models.TextField(help_text='Short description of the challenge', max_length=150, verbose_name='Short challenge description'),
        ),
    ]
