# Generated by Django 3.0.11 on 2021-08-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210820_1453'),
        ('challenge', '0006_remove_challenge_prticipants'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='prticipant_teams',
            field=models.ManyToManyField(blank=True, to='users.Team'),
        ),
    ]
