# Generated by Django 3.2.11 on 2022-01-29 06:22

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0009_challenge_timeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='winner',
        ),
        migrations.AddField(
            model_name='challenge',
            name='bronze_award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bronze_award', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='gold_award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_award', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='silver_award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silver_award', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Detailed descripton of the challenge'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='evaluation',
            field=ckeditor.fields.RichTextField(help_text='Detailed evaluation criteria'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='reward',
            field=ckeditor.fields.RichTextField(help_text='detailed reward structure'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='timeline',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Detailed timeline', null=True),
        ),
    ]
