# Generated by Django 3.2.11 on 2022-01-29 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0010_auto_20220129_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='alternate_reward',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Reward if its not monetary'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_monetary',
            field=models.BooleanField(default=False, verbose_name='Is the reward a cash prize?'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
