# Generated by Django 3.2.11 on 2022-01-30 07:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0012_auto_20220129_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='submission_email',
            field=models.EmailField(default='codershq@ai.gov.ae', max_length=254, verbose_name='Email for submission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='rules',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Rules related to submission (optional)', null=True, verbose_name='Rules (optional)'),
        ),
    ]
