# Generated by Django 3.0.11 on 2021-02-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='title',
            field=models.CharField(default='this is the title', max_length=100, verbose_name='Title of Hackathon'),
            preserve_default=False,
        ),
    ]
