# Generated by Django 3.0.11 on 2021-02-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_hackathon_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='slug',
            field=models.SlugField(default='this-is-slug', unique=True),
            preserve_default=False,
        ),
    ]
