# Generated by Django 3.0.11 on 2021-02-11 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_auto_20210209_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='hackathon_type',
            field=models.CharField(choices=[('VI', 'Virtual'), ('PH', 'Physical'), ('HY', 'Hybrid')], default='VI', max_length=2, verbose_name='Hackathon Type'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='last_join_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Last date competitors can join'),
            preserve_default=False,
        ),
    ]
