# Generated by Django 3.0.11 on 2021-02-11 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_auto_20210211_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='When the competitors can start joining', verbose_name='Hackathon join date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='date_end',
            field=models.DateField(help_text='Hackathon end date, no competitor can join after this date', verbose_name='Hackathon end date'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='description',
            field=models.TextField(help_text='Describe the Hackathon', max_length=5000, verbose_name='Hackathon description'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='evaluation',
            field=models.TextField(help_text='Describe how will the hackathon be evaluated', max_length=5000, verbose_name='Hackathon evaluation'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='last_join_date',
            field=models.DateField(help_text='Last date competitors can join', verbose_name='Last join date'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='prizes',
            field=models.TextField(help_text='Describe how the prize money will be distributed', max_length=5000, verbose_name='Hackathon prize distrebution'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='rules',
            field=models.TextField(help_text='Describe rules for the hackathon', max_length=5000, verbose_name='Hackathon rules'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='timeline',
            field=models.TextField(help_text="Describe the Hackathon's timeline", max_length=5000, verbose_name='Hackathon timeline'),
        ),
    ]
