# Generated by Django 3.0.11 on 2021-02-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0006_auto_20210211_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='hackathon_type',
            field=models.CharField(choices=[('VI', 'Virtual'), ('PH', 'Physical'), ('HY', 'Hybrid')], default=('HY', 'Hybrid'), max_length=2, verbose_name='Hackathon Type'),
        ),
    ]
