# Generated by Django 3.0.11 on 2021-02-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_auto_20210215_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='subtile',
            field=models.CharField(default='Subtitle', max_length=150, verbose_name='Subtitle'),
            preserve_default=False,
        ),
    ]
