# Generated by Django 3.0.11 on 2021-02-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0009_auto_20210215_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='subtitle',
            field=models.CharField(max_length=150, verbose_name='Little info to explain the Hackathon.'),
        ),
    ]
