# Generated by Django 3.0.11 on 2021-08-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='logo/', verbose_name='Company logo'),
        ),
    ]
