# Generated by Django 3.0.11 on 2021-08-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
