# Generated by Django 3.2.11 on 2022-03-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(max_length=200, verbose_name='Roles'),
        ),
    ]
