# Generated by Django 3.2.11 on 2022-02-28 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='portfolio_field_description')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='portfolio_field_githubUrl')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='portfolio_field_linkedinUrl')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='portfolio_field_websiteUrl')),
                ('twitter_handle', models.CharField(blank=True, max_length=50, null=True, verbose_name='portfolio_field_twitterHandle')),
                ('is_contributor', models.BooleanField(default=False, verbose_name='portfolio_field_isContributor')),
                ('contributor_level', models.SmallIntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=0, verbose_name='portfolio_field_contributorLevel')),
                ('is_admin', models.BooleanField(default=False, verbose_name='portfolio_field_isAdmin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('proficiency', models.SmallIntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], verbose_name='Proficiency')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('education_level', models.CharField(max_length=50)),
                ('end_date', models.DateField(verbose_name='Course end-date')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='award_field_awardName')),
                ('date_awarded', models.DateField(default=django.utils.timezone.now, verbose_name='award_field_awardDate')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
    ]
