# Generated by Django 3.2.11 on 2022-10-08 10:53

import codershq.portfolio.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='academic_qualification',
            field=models.CharField(blank=True, max_length=30, verbose_name='Your highest academic qualification'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='employment_time',
            field=models.CharField(blank=True, choices=[('F', 'Fulltime'), ('P', 'Part-Time')], max_length=1, null=True, verbose_name='Do you like to work full-time or part-time?'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='fav_language',
            field=models.CharField(blank=True, help_text='This can be a language or framework', max_length=50, null=True, verbose_name='Whats your favourite language?'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='personal_site',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator], verbose_name='Do you have a personal site?'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=codershq.portfolio.models.user_image_path, verbose_name='Profile image'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='proud_project',
            field=models.TextField(blank=True, help_text='This can be any project that you were involved in', max_length=2500, verbose_name='Tell us about the project that you are most proud of'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='years_experience',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Years of experience'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='github',
            field=models.CharField(blank=True, help_text='https://github.com/Coders-HQ', max_length=100, null=True, validators=[django.core.validators.URLValidator], verbose_name='Github account'),
        ),
    ]
