# Generated by Django 3.2.11 on 2022-03-01 17:23

import codershq.portfolio.models.model_project
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status', models.CharField(max_length=50, verbose_name='jobprofile_field_jobStatus')),
                ('hourly_rate', models.FloatField(default=5.0, verbose_name='jobprofile_field_hourlyRate')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='education_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='education_field_educationLevel'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(verbose_name='education_field_endDate'),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=50, verbose_name='education_field_name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50, verbose_name='language_field_name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='proficiency',
            field=models.SmallIntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], verbose_name='language_field_proficiency'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=100, verbose_name='task_field_name')),
                ('t_description', models.CharField(max_length=300, verbose_name='task_field_description')),
                ('t_difficulty', models.CharField(max_length=50, verbose_name='task_field_difficulty')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='task_field_endDate')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='service_field_name')),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.jobprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='project_field_name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='project_field_description')),
                ('image', models.ImageField(upload_to=codershq.portfolio.models.model_project.project_image_path, verbose_name='project_field_image')),
                ('link', models.URLField(blank=True, null=True, verbose_name='project_field_url')),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.jobprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_role', models.CharField(max_length=50, verbose_name='contribution_field_role')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.task')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Ambassador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=254, verbose_name='ambassador_field_studentEmail')),
                ('student_phone', models.IntegerField(verbose_name='ambassador_field_studentPhone')),
                ('university_name', models.CharField(max_length=60, verbose_name='ambassador_field_university')),
                ('responsibilities', models.CharField(max_length=60, verbose_name='ambassador_field_responsibilities')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='ambassador_field_startDate')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='ambassador_field_endDate')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
    ]
