# Generated by Django 3.2.11 on 2022-03-04 13:56

import codershq.portfolio.models.model_project
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20220301_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=codershq.portfolio.models.model_project.project_image_path, verbose_name='project_field_image'),
        ),
    ]
