# Generated by Django 3.2.11 on 2022-03-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_profile',
        ),
    ]
