# Generated by Django 3.2.11 on 2022-10-09 06:25

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20221008_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='country_residence',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
