# Generated by Django 3.2.11 on 2022-10-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20221009_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='consent_to_share',
            field=models.BooleanField(default=False, verbose_name='Do you conesent on sharing the data your provided and the assessment scores with potential employers?'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='is_seeking_job',
            field=models.BooleanField(default=False, help_text='Are you looking for employment?', verbose_name='Seeking employment?'),
        ),
    ]
