# Generated by Django 3.2.11 on 2022-04-06 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20220318_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='education_field_endDate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Where are you based in?'),
        ),
    ]
