# Generated by Django 3.2.11 on 2022-10-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20221009_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='consent_to_share',
            field=models.BooleanField(default=False, help_text='Do you conesent on sharing the data your provided and the assessment scores with potential employers?', verbose_name=''),
        ),
    ]
