# Generated by Django 3.2.11 on 2022-10-09 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_portfolio_consent_to_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='consent_to_share',
        ),
    ]
