# Generated by Django 3.2.11 on 2022-04-06 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20220406_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=60, verbose_name='Job title')),
                ('start_date', models.DateField(verbose_name='Job start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Job end date')),
                ('is_current', models.BooleanField(default=False, verbose_name='Currently working on this?')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
    ]
