# Generated by Django 3.2.11 on 2022-04-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_experiance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experiance',
            new_name='Experience',
        ),
    ]
