# Generated by Django 3.2.11 on 2022-10-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_portfolio_consent_to_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='academic_qualification',
            field=models.CharField(max_length=30, verbose_name='Your highest academic qualification'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='employment_time',
            field=models.CharField(blank=True, choices=[('F', 'Fulltime'), ('P', 'Part-Time')], max_length=1, null=True, verbose_name='Would you prefer to work full-time or part-time?'),
        ),
    ]
