from .language_admin import LanguageAdmin
from .education_admin import EducationAdmin
from .portfolio_admin import PortfolioAdmin
from .award_admin import AwardAdmin
from .task_admin import TaskAdmin
from .contribution_admin import ContributionAdmin
from .ambassador_admin import AmbassadorAdmin
from .project_admin import ProjectAdmin
from .service_admin import ServiceAdmin
from .jobProfile_admin import JobProfileAdmin
